### ISSUE TITLE
Use of Context.SaveChanges() in Create() method of EF Repository

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Brochard#10]
Related to Create(T entity) method within EF repository to what extend is useful to use Context.SaveChanges() within Create method? 
I mean, I understand you use it for having available for next queries the entitity you just added. But it is an expesive price for having this commodity. In your opinion is this commodity really a need? 
I mean in Orchard 1.8 the current code that consumes Repository really harness this commodity? 
How much code? Can you point me an example? Will it be difficult to change that code that adds and consumes data to delegate on it the decission of when to call context.SaveChanges()?

**Comment by Jetski5822** [comment]
Yes it is an expensive commodity - it's one of the things I really dislike about EF - there is a lot I like, but this one area does bug me. I think it should be added in by settings, like "AutoFlush" : true within a config file.

**Comment by jersiovic** [comment]
What exactly you mean with the Autoflush feature? What do you expect it does? When would it save data? With this  autoflush features you would expect that when you query the context any created data but not saved in db would be returned because if it still is not saved previously EF will save it? Is this what you mean?

Enviado desde mi Windows Phone
________________________________
De: Nicholas Mayne<mailto:notifications@github.com>
Enviado: ‎31/‎01/‎2015 11:31
Para: OrchardCMS/Brochard<mailto:Brochard@noreply.github.com>
CC: jersiovic<mailto:jersio@hotmail.com>
Asunto: Re: [Brochard] Use of Context.SaveChanges() in Create() method of EF Repository (#10)

Yes it is an expensive commodity - it's one of the things I really dislike about EF - there is a lot I like, but this one area does bug me. I think it should be added in by settings, like "AutoFlush" : true within a config file.

---

**Comment by Jetski5822** [comment]
The idea of AutoFlush would be that if you add/update an object, a call to SaveChanges is made.

Or alternatively, if you add/update an object we set a isdirty flag, then when making a query that involves that object, we call save changes and then the query will return everything.

Not sure...

**Comment by jersiovic** [comment]
I see, I think both alternatives are expensive.
The point is why do you need that? Do you have many code where you need to mix in memory data pending of being added with data in the db? Can you point me code in Orchard that has this need. I don't know too many of Orchard but I suspect we are worried for something we don't have any need.

**Comment by Jetski5822** [comment]
Removed Repository pattern.
