### ISSUE TITLE
Building Brochard on OSX?

### ISSUE THREAD

**Issue by christianscheuer** [OrchardCMS/Brochard#18]
Dear Orchard/Brochard devs.
Thank you for some amazing work in porting this CMS to the new ASP.net v5.
I am having issues building this on OSX though.

It seems that you are building against the latest available beta5 bits from the unstable feed. So I am using the beta5-11744 mono build of the DNX. However, after succesfully restoring packages using "dnu restore", I am getting errors complaining the IApplicationBuilder and IServiceCollection classes (referenced in the Startup.cs file) couldn't be found, when I run the "dnx . kestrel" command (this is after adding a kestrel command to the project.json).

Do you have any clues on how to get this building on OSX? Or should I be using an older build of beta5?

**Comment by Jetski5822** [comment]
@christianscheuer Hey, the main target at the moment is for the solution to run on CoreCLR so than we can be as close to OSX compatible as possible - I cant say we are OSX compatible, as I personally have not tested it on OSX, just CoreCLR compatible.

As for the missing dependencies, beta5 is totally right, so thats good.

I investigated a little in to this, and have you taken a look at http://stackoverflow.com/questions/29007962/how-can-i-diagnose-missing-dependencies-or-other-loader-failures-in-dnx ?

**Comment by christianscheuer** [comment]
@Jetski5822 Great, thank you for your quick reply. CoreCLR as your primary focus makes perfect sense.

Unfortunately, dnu restore currently has known bugs in beta5-11744 on CoreCLR/OSX, so the build process on OSX at the moment is quite terrible. I guess I will have to be more patient and wait for some fixes (maybe even a stable CoreCLR beta for OSX) before I try again :-)

**Comment by christianscheuer** [comment]
@Jetski5822 I managed to get the DNX versions cleaned up on my system and narrow down the cause of the issue. It seems the new package version resolving process works better if you omit the 'beta5' tag. I noticed this also had been removed from the "latest" samples in the official aspnet/Home repo. Without those, it almost compiled. I then found out the ApplicationBuilder class had changed namespace, which I fixed, and then it compiled.

To debug with OSX I added a kestrel command.
There were a few issues when running on OSX which I fixed as well - namely a String.Replace call, which transformed forward slashes to backslashes. This caused the discovery of Site configurations etc. to not work, leaving a blank output in the browser. When fixed, the text hello world text gets correctly displayed for Test2.

I have collected all of these fixes into this pull request:  #19 

Please let me know if you have a preferred way of receiving contributions, or if you would have preferred these changes as separate commits. This is my first pull request, so bare with me :)

**Comment by Jetski5822** [comment]
PR looks good, so I have taken it in, thanks :+1: - I will need to check the String Replace when I get home, and maybe wrap a IsMono check around it if it does not work on Windows, but either way it should work on OSX.

**Comment by christianscheuer** [comment]
Great - thank you for accepting my first pull request :-) :+1: 
Yeah I figured something like that needs to be done. Remember the check should really be for *nix vs. Windows, and not mono, since both mono and coreclr will need forward slashes on *nix systems. Let me know if you need me to check which defines are present.
Another options is to use System.IO.Path.DirectorySeparatorChar.
https://msdn.microsoft.com/en-us/library/system.io.path.directoryseparatorchar(v=vs.110).aspx

**Comment by Jetski5822** [comment]
Using System.IO.Path.DirectorySeparatorChar would be a much better option, that way we wont need to differentiate between environments.
