### ISSUE TITLE
Should Brochard offer UoW pattern through IContentStore?

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Brochard#20]
This issue is to discuss if the UoW pattern is a need to fulfill in Brochard or not
Discussion started in the middle of a commit: https://github.com/OrchardCMS/Brochard/commit/327cd9b43667e975a036fc2d66ee6aaa3c2696a1#commitcomment-11269146

**Comment by jersiovic** [comment]
My opinion.
If I only pay attention to what I get from UoW pattern I prefer to have it, because it helps me to make simpler code when I retrieve contents through IContentStore that I need to process in an algorithm that can change or not some of those contents. I don't need to include code that updates those contents only if they are changed. This duty is delegated on the IContentStore when it implements UoU.
If I pay attention to the cost of developing an implementation of IContentStore with UoW behavior is when doubts arise. Even though I don't think it should be difficult.
I did it previously on a private project with Siaqodb db (that OO db doesn't provide an UoW service). Problem is I did it based on Property Changed events that were raised by setters of the properties of my contents. In Brochard we don't have that Property Changed events (in fact I don't think it is the right solution). Instead, we can use a similar approach to what EF tracker does.
At this point, maybe we should take a look to EF7 to see how its tracker works and maybe use it or borrow it for our alternate implementations (based on stored procedures, or others).
Thinking it twice, the only thing EF7 offers us when we'll use EF7 for accessing NoSQL dbs is the UoW pattern and LINQ queries, other duties will be delegated on the EF7 Provider specific for a concrete db. 
So, why do not investigate a bit how EF7 has abstracted their providers to see if it is interesting to use EF7 as our UoW implementation for all our IContentStore implementations, and offer alternate providers for the different storages we want to support?

**Comment by bleroy** [comment]
I think some of the assumptions related with UoW that we made when we initially designed Orchard need to be challenged, although I'm not sure what the solutions are. But here goes, to get the conversation started:

* ambient transaction: even though transactions are also useful when only reading, the default settings for that transaction unnecessarily slow things down by assuming that there will be writes. In a CMS however, writes are the exception, and most requests are read-only.
* implicit persistence and commits: changes to entities get automatically and mysteriously persisted, if the transaction is not rolled back, which is somewhat surprising to new users. I've come to prefer more explicit persistence, still framed with transactions.
* change tracking: it's not always clear what objects track changes, and what objects don't. In a document-driven storage system, the requirement to track changes is not as strong, and way less complex, as there are less relationships to keep track of.

**Comment by jersiovic** [comment]
@bleroy I totally agree first two points have a room for improvement in the sense you point.
* ambient transactions: by default shouldn't be used.
* implicit persistence and commits: much better explicit persistence

However, related to third point I don't agree due two reasons.
* First, because change tracking still is useful to kwow which of the documents of a set has been changed in situations where you have to store changed ones after process them.
* Second, because I think it would be better to maintain Orchard as agnostic of the technology of storage as possible. When you think in document-driven storage to decide if change tracking is needed, you are taking a decission based on a a technology (document-driven storage). What if in a near future we test hibrid dbs (Graph-document dbs) and those improve performance of queries retrieving documents pointing to other documents? At this point change tracking would matter. Why renounce to this possibility by a design decission?

**Comment by bleroy** [comment]
Can you elaborate on a scenario when only some of the documents in a collection need to be persisted, and you couldn't as easily know without tracking?

I'm not assuming a storage technology, just that the high-level API will deal with documents. In Decent, I already have three different storage technologies under the same document-centric API.

Content items are documents, it's a fact of CMS that unfortunately few CMS recognize (including Orchard), and it makes their data API awkward. I think that's what we're trying to fix.

Now there remains questions about non-content-item data, but our first scenario is content.

**Comment by jersiovic** [comment]
You are right is difficult to find a sample for simple documents. All the scenarios I can think where tracking really helps me are those not based only on documents. I mean it would be a help in document-graph dbs. For example if you have a Product document that has Content-Item field called Supplier that links it to an external Supplier document. And this Supplier document has a Content-Items field called Products that links to all the Products it supplies.
If I remove a Product from the Products list of a Supplier my code will change the Supplier of the Product Document to null. This change in Product Document needs to be tracked to help me simplify storage. 

I agree content-items are documents  but why documents cannot have links to other documents that can improve a lot queries performance. So I think is worth to take into account the Document-graph dbs to put things easy to harness them.

What if for previous scenario I want to get all the products with its Supplier?
Which steps will do a pure document db?
An hybrid db supporting LINQ should allow us in theory to get them in very fast way (faster than a relational db or an document db): 
dbContext.Products.Where(p=>p.Description.Contains("soap").Include("Supplier")

What if for previous scenario I want to get all the products that belongs to suppliers located in Spain?
Which steps will you do with a pure document db for creating this query?
An hybrid db supporting LINQ should allow us in theory to get them in very fast way (faster than a relational db or an document db): 
dbContext.Products.Where(p=>p.Supplier.Country=='Spain')

**Comment by jersiovic** [comment]
The point is if you remove tracking from IContentStore, all the code which consumes this interface will be written with that in mind. If in the future you want to take profit of tracking for hybrid dbs, the code written by all the consumer classes till that date will be broken.

**Comment by bleroy** [comment]
Documents can have references to other documents, but they should not in most cases. Furthermore, those links themselves will be an id somewhere in the document, which an ORM won't be able to track.

Query performance is irrelevant if we decide to separate querying from storage, using a map/reduce type of querying API: in that case the storage schema, even with relations between documents, doesn't matter as you'll flatten all that into an index, and then that's what you query. Your product-supplier scenarios are covered with simple indexes.

**Comment by jersiovic** [comment]
Well, there are other places where those links will be useful, like Taxonomy Terms and this is a very important topic in Orchard
In the case of document databases as you say those links are simply ids (foreign keys) pointing to external documents that an ORM cannot track if you store in that way.
The question is; EF7 that that will support NoSql dbs will it support to use navigation properties when underlying storage is a DocumentDb or a Graph-documentdb? If the answer is yes then it means we can store those relations as Navigation properties and it will do the dirty work under the hoods.

The steps needed to get all the products with its Supplier or to get all the products in a taxonomy term, will be very diferent in performance terms if you use an hibrid db or a model without navigation properties like the one you propose.
The steps with navigation properties + hibrid db + EF:
* Query index to get the taxonomy term id by term name
* dbContext.TaxonomyTerms.FirstOrDefault(p=>p.Id==termId).Include("Products")
  this only query to the db engine is specially fast in a graph db because retrieving the TaxonomyTerm it has the phisical addressed in disk where referenced Products are stored because they are stored within the TaxonomyTerm. So db engine retrieves each Product directly from its postion in disk in one step.
The steps without navigation properties + hibrid db + EF:
* Query index to get the taxonomy term id by term name
* taxonomyTerm = dbContext.TaxonomyTerms.FirstOrDefault(p=>p.Id==termId)
* foreach (productId in taxonomyTerm.ProductIds) {dbContext.Products.FirstOrDefault(p=>p.Id==productId)}
This time you need make a call to db per each product in the TaxonomyTerm (instead of one like in previous scenario)  and each of this calls needs two steps by the db engine (instead of one like in previous scenario): first retrieves the position in disk from an index, second retrieves the product from the address in memory. 

I think the difference in performance will be relevant.

Related to map/reduce API I like the idea but I still see it as a black box. Can you point me a sample with an approximation of the consumer code that will create indexesfor queries like the ones in scenarios I proposed where there are relations between documents to have a clear idea of what you propose?

**Comment by bleroy** [comment]
Well, the way it would happen is that you'd be able to move the costly part of the request to the indexing phase, where performance is less crucial. The way if would work is that the map function would create an index entry for each term, with a value that contains the list of associated products, with as much or as little details as you want. When querying that index, you'd just access the entry for the term(s) you're looking for. That's an extremely cheap operation.

But I'm thinking that it may be a little too radical to do all querying through the map/reduce API, and if we leave other, more conventional possibilities, then your points stand.

**Comment by jersiovic** [comment]
I see, it looks better to maintain both paths open. 

Related to how EF does change tracking and its impact on performance. I would spect that EF7 document db or hibrid db providers would offer its own change tracker that provides a lighter change tracking aware of the nature of documents. But this pure speculation I'm looking for information related with this. By the moment I have asked the question to Athur Vickers in his interesting post related to how to develop a providerf for EF7
http://blog.oneunicorn.com/2015/05/07/ef7-provider-building-blocks-2/#comment-10655

**Comment by Jetski5822** [comment]
The UOF pattern is provider specific.... as only the content store which wraps the storage can dictate how to persist and track data - so this will also leave both paths open.
