### ISSUE TITLE
DbContextOptionsBuilder renamed to EntityOptionsBuilder

### ISSUE THREAD

**Issue by BilalHasanKhan** [OrchardCMS/Brochard#23]
I think the class DbContextOptionsBuilder has been renamed to EntityOptions builder in latest EF7 code.
I did a pull request for that in Brochard but seems now it has been overwritten, or am I missing some point?

**Comment by Jetski5822** [comment]
I think they renamed it back...

https://github.com/aspnet/EntityFramework/search?utf8=%E2%9C%93&q=EntityOptions&type=Code

https://github.com/aspnet/EntityFramework/search?utf8=%E2%9C%93&q=DbContextOptionsBuilder

I changed it in changeset https://github.com/OrchardCMS/Brochard/commit/1eb981b004dd9a081d08f1270760f8a50e6cea94

**Comment by BilalHasanKhan** [comment]
Ok. sorry to bother you with this should have taken latest first :)

**Comment by Jetski5822** [comment]
Its cool :)
