### ISSUE TITLE
Change IoC

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Brochard#25]
The current IoC container we use is limiting in it's features, i.e. it doesnt support Lazy<> and wont.

So, look to implement Autofac or DryIoC

**Comment by Jetski5822** [comment]
Branch for Autofac here: https://github.com/OrchardCMS/Brochard/tree/Autofac

**Comment by Jetski5822** [comment]
Moving list to Trello

**Comment by sfmskywalker** [comment]
Can we reopen this? I need the ability to inject a `Func<IEnumerable<TSomething>>`. I'll submit a PR.

**Comment by Jetski5822** [comment]
@sfmskywalker you want to change DI?

**Comment by Jetski5822** [comment]
Maybe we can add extension methods similar to this issue https://github.com/aspnet/DependencyInjection/issues/98

**Comment by sfmskywalker** [comment]
@Jetski5822 Well, I primarily want support for Lazy<T> and Func<T> so yeah, the extension method solution would work too. The only other benefit of using another DI provider I can think of right now is that it might have better support for child containers.
