### ISSUE TITLE
Cann't access Brochard website

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/Brochard#31]
I followed the steps in **README.md**, I started the server an throws ```WebListernerException``` I fixed by run the dnx command with administrator privileges, now the server is running, but whenever I'm trying to access http://local.orchardvnext.test1.com/home/index "Server not found" message show up in the browser

**Comment by gvx111** [comment]
you must add local.orchardvnext.test1.com domain in system32/drivers/etc/host

**Comment by hishamco** [comment]
I already did that :smile:

**Comment by Jetski5822** [comment]
Can you try  http://local.orchardvnext.test1.com/setup/index ?

**Comment by hishamco** [comment]
Same thing :(

**Comment by Jetski5822** [comment]
It was my fault - I made a bad check in. I just pushed a fixed :)

**Comment by hishamco** [comment]
I fetch and rebase, but same thing the server is running but I can't access the url?!!

**Comment by Jetski5822** [comment]
Same error??? Did you go setup/index?

**Comment by Jetski5822** [comment]
Hang on, server not found? Sure you have setup your host file to talk to localhost correctly?

Are you on windows?

**Comment by hishamco** [comment]
Yep I did, loading after that I get server not found.
I already added "127.0.0.1       http://local.orchardvnext.test1.com" in hosts file

**Comment by Jetski5822** [comment]
127.0.0.1 local.orchardvnext.test1.com

No http in host file.

**Comment by hishamco** [comment]
Thanks @Jetski5822 finally it works, it's my fault :(
