### ISSUE TITLE
Question about Area

### ISSUE THREAD

**Issue by gvx111** [OrchardCMS/Brochard#36]
I Create new module and i want to route all controller like {area}/{controller}/{action} where {area} default is admin. but when i make this route for this module doesnt working. I tried to add controller attribute area and also Route but result was blank page.
How can i make custom route for module.

**Comment by Jetski5822** [comment]
Can you paste in the code for the route?

**Comment by gvx111** [comment]
return new[] {
                new RouteDescriptor {
                    Route = new Route(
                        null,
                        "admin/{controller}/{action}",
                        defaults:  new
                            {
                                area = "ITN.TS.Administrator",
                                controller = "Home",
                                action = "Index"
                            },
                        dataTokens:  new
                            {
                                area = "ITN.TS.Administrator"
                            }
                        )
                }
            };

**Comment by Jetski5822** [comment]
try setting the name to something.... I noticed an issue with that,.

return new[] {
                new RouteDescriptor {
                    Route = new Route(
                        "Test",
                        "admin/{controller}/{action}",
                        defaults:  new
                            {
                                area = "ITN.TS.Administrator",
                                controller = "Home",
                                action = "Index"
                            },
                        dataTokens:  new
                            {
                                area = "ITN.TS.Administrator"
                            }
                        )
                }
            };

**Comment by gvx111** [comment]
<pre>verbose : [Microsoft.Net.Http.Server.WebListener] Sending Response: HTTP/1.1 404
 Not Found; Headers: { X-Generator: ITN; Content-Length: 0; }</pre>
same text;

**Comment by gvx111** [comment]
I fixed this problem but we have also another problem about Url.Action. Url.Action Can not generate path of action. I write extension of IUrlHelper but it is not the best way.
<pre>
 public static class ModuleHelper
    {
        public static string ModuleAreaName { get; set; }
        public static string ModuleArea(this IUrlHelper path, string content)
        {
            return path.Content($"~/Modules/{ModuleAreaName}/{content}");
        }

        public static string ModuleAction(this IUrlHelper path, string controller, string action)
        {
            return $"~/admin/{controller}/{action}";
        }
        public static string ModuleAreaView(this IUrlHelper path, string content)
        {
            return path.Content($"~/Modules/{ModuleAreaName}/Views/{content}.cshtml");
        }
    }
</pre>

**Comment by Jetski5822** [comment]
Will do this once I hit the UI story
