### ISSUE TITLE
Accepting contributions?

### ISSUE THREAD

**Issue by jrestall** [OrchardCMS/Brochard#37]
Hi Nick,

Are you currently accepting contributions to Orchard vNext?

When I have time I'd like to help out but could do with some guidance on what tasks I could submit a pull request for.

Perhaps if there was a list of issues that followed the advice given [here](http://radek.io/2015/08/24/github-issues/) it would be easier for myself and others to help out?

The task list could be as simple as:
- [ ] Migrate event bus [Beginner]
- [x] Migrate caching [Intermediate]
- [x] Implement localization [Bigger Project]
- [x] Implement security module [Bigger Project] [Question]
- [x] Shapes [Bigger Project]
- [x] Remove OrchardVNext naming [Beginner]
- [x] How to package the many framework modules [Bigger Project] [Question]

**Comment by Jetski5822** [comment]
Hey, Always accepting contributions!

I have a trello board that is public (https://trello.com/b/cmgxjNN5/brochard) but I can see that having things in Github would probably be much nicer so will take a look at getting that done.

N

**Comment by Jetski5822** [comment]
https://github.com/OrchardCMS/Brochard/issues/38
