### ISSUE TITLE
IModule [Question]

### ISSUE THREAD

**Issue by gvx111** [OrchardCMS/Brochard#42]
How can i use IHostingEnvironment; I have class like this:
<pre> public class RegisterServices : IModule
    {
        public void Configure(IServiceCollection serviceCollection)
        {
            serviceCollection.AddScoped< IAdminAreaRegister, AdminAreaRegister >();
            serviceCollection.AddScoped< IAuctionRepository, AuctionRepository >();
            var t = serviceCollection.BuildServiceProvider().GetService < IHostingEnvironment > ();
        }
    }</pre>
but t is null. Can not take IHostEnvironment.

**Comment by Jetski5822** [comment]
does IHostingEnvironment get resolved in the ctor?

**Comment by gvx111** [comment]
Yes in Controller ctor resolved. but in IModule not. Assambly Activator can't: Error MSG:No parameterless constructor defined for this object.
I want take application path. I also tried to activate IHostingEnvironment but t is null.

**Comment by Jetski5822** [comment]
How upto date is your Brochard codebase?

**Comment by gvx111** [comment]
I have lastest. i updated yesterday.

**Comment by Jetski5822** [comment]
I just pushed a change, it will now resolve everything in host scope.

**Comment by gvx111** [comment]
Solved. Great. Thank you very much :))
