### ISSUE TITLE
DNX React. [Bug]

### ISSUE THREAD

**Issue by gvx111** [OrchardCMS/Brochard#43]
System.InvalidOperationException: This application requires DNX version 1.0.0-be
ta8-15665 or newer to run.

**Comment by gvx111** [comment]
after this 

System.IO.FileLoadException: Could not load file or assembly 'Orchard.Logging.Co
nsole' or one of its dependencies. Method does not exist. (Exception from HRESUL
T: 0x80131513)

**Comment by tstar** [comment]
Maybe it will help you https://github.com/aspnet/dnx/issues/2824.

**Comment by gvx111** [comment]
It's not problem of DNX. Error Message is:
<pre>
System.IO.FileLoadException: Could not load file or assembly 'Orchard.Logging.Console'

**Comment by Jetski5822** [comment]
We have updated the nuget config file
