### ISSUE TITLE
Plug in a real logger.

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Brochard#5]
At the moment we have just a static console logger called FakeLogger. Lets get a real one in there and allow it to be easily swap-able.

**Comment by hishamco** [comment]
I'm planning to create ```FileLoggerProvider``` that we can subclasses and allow us to create a variety of file logger such as  ```TextLoggerProvider```,  ```XmlLoggerProvider``` .. etc

So can can I make a PR , or shall I write a sample code to show you my humble design?

**Comment by Jetski5822** [comment]
Argh, my comment didn't save. 

I think its a good idea to give it a go, have you seen the https://GitHub.com/aspnet/logging work?

I'll comment more tomorrow as on phone at mo.

**Comment by hishamco** [comment]
Of course and I did a humble PRs, so shall I make a PR or write a code snippet first

**Comment by Jetski5822** [comment]
Lets take a look at a code snippet :)

**Comment by hishamco** [comment]
Sure :smile:

**Comment by hishamco** [comment]
https://github.com/aspnet/Logging/issues/201

**Comment by Jetski5822** [comment]
So, create a LoggingModule : IModule, add add a Logger based on configuration. Then if we want to log to a file, its just configuration.

Make the default NLog? Or console?

Whatcha think?

**Comment by hishamco** [comment]
Of course the configuration is very handy in almost the providers: logging, authentication .. etc. The ```ConsoleLogger``` is good as default logging provider, also we may need sort of ```CompositeProvider``` to log into different sources at one shoot, let me take the initiative :smile: , I planned to do that from few weeks ago but I stuck every time on launching the url, I appreciate your effort to make the fix, it is time to move into this :+1:

**Comment by hishamco** [comment]
@Jetski5822 I faced some issues:
1- I got ```MissingMethodException``` in ```GetRefrencingLibraries``` whenever i'm trying to run unit test
2- Is there a default configuration file that we can put the logger settings
3- If I create a ```LoggingModule``` that implement ```IModule```, is the DI of ```IServiceCollection``` done out of the box, or shall I do some extra stuff

**Comment by Jetski5822** [comment]
Okay done! To plug in another logger we just need to create a module and implement the ILoggingInitiator interface. This will then get added to the Logger pipeline at the ApplicationServices level.

i.e.

    public class LoggingInitiator : ILoggingInitiator {
        public void Initialize(ILoggerFactory loggerFactory) {
            loggerFactory.AddConsole(LogLevel.Debug);
        }
    }

For NLog

    public class LoggingInitiator : ILoggingInitiator {
        public void Initialize(ILoggerFactory loggerFactory) {
            loggerFactory.AddNLog(LogLevel.Debug);
        }
    }
