### ISSUE TITLE
IEventNotifier [Bug]

### ISSUE THREAD

**Issue by gvx111** [OrchardCMS/Brochard#52]
I have return type of method string and making exception:
Exception MSG:
<pre>An exception of type 'System.InvalidOperationException' occurred in System.Core.dll but was not handled in user code

Additional information: Sequence contains no elements</pre>
File: DefaultOrchardEventNotifier
Method: GetGenericMethod
Parameters: 
Type = {Name = "Enumerable" FullName = "System.Linq.Enumerable"}
name = OfType
genericArgTypes = {System.Type[0]}
argTypes[1] = {Name = "IEnumerable" FullName = "System.Collections.IEnumerable"} at 0 index
returnType = {Name = "IEnumerable`1" FullName = "System.Collections.Generic.IEnumerable`1"}

**Comment by Jetski5822** [comment]
Werid.... Im am going to swap out the DI to make things a bit easier, so the events module might change slightly
