### ISSUE TITLE
Different Module locations

### ISSUE THREAD

**Issue by benschi11** [OrchardCMS/Brochard#7]
Maybe a little bit early but one of the biggest things I miss in Orchard currently is to specify different module directories. I know the problem is that every module is a mvc area and they need this structure but maybe you can bear it in mind :).

**Comment by bleroy** [comment]
Interestingly, that capability has existed from the start: this is how Core modules can be loaded. Because it happens so early in bootstrapping however it's tricky to find where this could be configured. Maybe in settings.txt.

**Comment by Jetski5822** [comment]
I think at the moment you have to actually create a implementation of IExtensionFolders and add it to OrchardStarter. note ModuleFolders and CoreModuleFolders

**Comment by benschi11** [comment]
@bleroy I didn't know that - I will take a look as soon as I can find time.

My dream would be to have one Orchard Installation for every Version on your computer and use it for all my projects :) - but I am not sure if thats possible ;)

**Comment by bleroy** [comment]
Well, you're kind of describing multi-tenancy. Kind of. But that's an interesting idea.

**Comment by Piedone** [comment]
Also see for the same: https://orchard.codeplex.com/workitem/21190

**Comment by Jetski5822** [comment]
Need to look at making this dependent on configuration..... global.json?
