### ISSUE TITLE
Dependency resolution in middlewares doesn't work as of ecdfd16

### ISSUE THREAD

**Issue by jasper-d** [OrchardCMS/Brochard#8]
Running latest version in master (ecdfd16) from VS CTP 5 using k web results in a NRE in[OrchardShellHostMiddleware](https://github.com/OrchardCMS/Brochard/blob/master/src/OrchardVNext/Environment/OrchardShellHostMiddleware.cs#L21). ShellSettings doesn't seem to be registered anywhere.
I tried to fix it, but it did more harm than good.

Similar problem in [OrchardRouterMiddleware](https://github.com/OrchardCMS/Brochard/blob/master/src/OrchardVNext/Routing/OrchardRouterMiddleware.cs#L20). IRouteBuilder is registered in ShellContainerFactory, but ShellContainerFactory.CreateContainer([...]) isn't called yet when the middleware is executed.

Environment: VS CTP 5, 1.0.0-beta3-10921 CLR x86

**Comment by Jetski5822** [comment]
Oddness - seems to be okay for me.

I am running on 1.0.0-beta3-10921   CLR     x86

I load up OrchardVNext sln, compile, then open a command prompt with admin privileges. I then do "k run"

**Comment by Jetski5822** [comment]
On the other hand, I dont think I checked in my dummy shell settings. - I have check in now, so can you do a pull?

**Comment by jasper-d** [comment]
Pulled, k web, works. Thanks!

**Comment by Jetski5822** [comment]
Welcome.
