### ISSUE TITLE
Why I can't run OrchardVNext.Demo.Home controller?

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Brochard#9]
Hello I'm just starting with ASP.NET vNext so maybe I'm having more questions than is usual.

I'm at the commit 732852ed16b18ffc932949662dc0250cc4d38480 (last one at entityframework branch). 
I have created a wwwRoot folder within OrchardVNext.Web in order to run the app because if it doesn't exists I get an error. To create manually this folder is what is expected?
If I debug the solution as it is I get an "Unable to locate project.json" message within an Error page.
However I'm able to debug the app replacing IIS Express per web in Debug Target properties of OrchardVNext.Web project. 

Problem is the app only runs when my url request is http://local.orchardvnext.test1.com or  http://local.orchardvnext.test2.com but nothing happens if I request http://localhost:61562

The only way I've managed to make the solution work in response to a http://localhost request has been adding localhost without port to web command in project.json 
 --server.urls http://localhost;http://local.orchardvnext.test1.com;http://local.orchardvnext.test2.com    
And removing the port from RequestUrlPrefix within App_Data\Sites\Default\settings.txt.

The point is when I call http://localhost/OrchardVNext.Demo/Home/Index middleware is run but Controller is never called.

Is it the normal behavior? I haven't managed to find why the controller doesn't work because  everything looks fine. Any help?
Regarding what I have had to do for making work the solution, is it normal? I imagine the change in the port is because when I use web command instead of IIS Express Visual Studio it is ignoring the port for debugging . But are you able to debug it with IIS Express?

**Comment by nicholaspei** [comment]
try this: http://local.orchardvnext.test1.com/Home/Index
it must be work.

**Comment by Jetski5822** [comment]
Yeah, so far we have only 1 route. and that is /Home/Index. So as @nicholaspei mentioned, try navigating to http://local.orchardvnext.test1.com/Home/Index

**Comment by jersiovic** [comment]
When I have read your answer I have thought: "I checked this it didn't work"
The point is it works! 
I should have tested it at some point when I had other problems

Thank you!
